### ISSUE TITLE
[Question] Example running error about PPO

### ISSUE THREAD

**Issue by LoveingStatistics** [Stable-Baselines-Team/stable-baselines3-contrib#196] opened 2023-07-20 02:49 UTC
### ❓ Question

![image](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/assets/50355838/859a9830-6a28-490b-a93d-e1b8789463ff)
Hello, I'm a rookie at RL, when I try to run the example on the sb3_contrib documentation, I encounter this issue, anyone can help?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-07-20 09:59
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1598

We probably need to revert the check as it was before (checking for `write` method only).

**Closed by araffin** 2023-07-20 09:59 UTC
Labels: duplicate, question

**Comment by araffin** [comment] 2023-07-20 11:48
I pushed a fix here: https://github.com/DLR-RM/stable-baselines3/pull/1615 could you give it a try? (see our doc on how to install from source)

**Comment by LoveingStatistics** [comment] 2023-07-20 23:45
It works, thanks for your help!
