### ISSUE TITLE
[Question] Apply Masking using ActionMasker on composite actions

### ISSUE THREAD

**Issue by mwalidcharrwi** [Stable-Baselines-Team/stable-baselines3-contrib#249] opened 2024-06-15 02:45 UTC
### ❓ Question

Hello, 

I am trying to apply ActionMasker on an action space of type `spaces.MultiDiscrete` and `MaskablePPO` model using the below action space definition:
self.action_space = spaces.MultiDiscrete([len(list1), len(list2)])

However I am getting a size mismatch when encoding the above action space to the `spaces.MultiDiscrete`

I tried looking through the issues list of the repository but what I found includes flattening the action and I was wondering is there any class method to handle MultiDiscrete without the need to do it manually?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by mwalidcharrwi** [comment] 2024-06-18 00:57
Dear @araffin 

To provide more information about the issue I am getting the below is what I encounter when the above action_space is defined:


  ```
File "/Users/opt/anaconda3/envs/code/lib/python3.8/site-packages/sb3_contrib/common/maskable/distributions.py", line 240, in apply_masking
    masks = masks.view(-1, sum(self.action_dims))
RuntimeError: shape '[-1, 49]' is invalid for input of size 37
```

it is worth mentioning that the length of list1 is 37 and list2 is 14. 

I saw some suggestions mentioning flattening the actions. However, I wanted to inquire if the MaskablePPO can handle it without the need to resize/modify the action dimension at all?

**Comment by araffin** [comment] 2024-06-23 11:00
> I tried looking through the issues list of the repository but what I found includes flattening the action and I was wondering is there any class method to handle MultiDiscrete without the need to do it manually?

I think there is a misunderstanding, if you look at the example env (in the repo) or at the issues, you need to flatten the action mask, not the actions.

**Comment by araffin** [comment] 2024-06-24 12:00
closing as duplicate of https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/80#issuecomment-2186409952

**Closed by araffin** 2024-06-24 12:00 UTC
Labels: question, more information needed
