### ISSUE TITLE
issue about Recurrent ppo

### ISSUE THREAD

**Issue by tingtingLiuLiu** [Stable-Baselines-Team/stable-baselines3-contrib#155] opened 2023-02-17 13:53 UTC
Hello, when I run RPPO , I set batch_size is 64. I found that the data obtained each time in the training phase is inconsistent with 64? Excuse me, what is this related to? And can you give me more information to understand RPPO?
Thanks

**Comment by tingtingLiuLiu** [comment] 2023-02-17 14:15
Hi,I found that these codes affected the results. Does this max_length refer to the length of an episode?
 n_seq = len(self.seq_start_indices)
 max_length = self.pad(self.actions[batch_inds]).shape[1] 
padded_batch_size = n_seq * max_length
Why should we follow the padded_batch_size to sample data?

**Comment by araffin** [comment] 2023-02-17 14:31
I guess it is a duplicate of https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/113

**Comment by tingtingLiuLiu** [comment] 2023-02-17 14:31
Hi
lstm_states_pi = (
            # (n_steps, n_layers, n_envs, dim) -> (n_layers, n_seq, dim)
            self.hidden_states_pi[batch_inds][self.seq_start_indices].reshape(n_layers, n_seq, -1),
            self.cell_states_pi[batch_inds][self.seq_start_indices].reshape(n_layers, n_seq, -1),
        ) 
Where, (n_steps, n_layers, n_envs, dim) ->(n_layers, n_seq, dim).
Does it mean that lstm obtains the status information of the whole episode, not the status information of the previous n steps?

**Comment by tingtingLiuLiu** [comment] 2023-02-17 14:37
> I guess it is a duplicate of #113

Thank you very much. I understand this problem.

**Closed** 2023-02-17 15:39 UTC
Labels: duplicate, question

**Comment by tingtingLiuLiu** [comment] 2023-02-18 02:15
> Hi lstm_states_pi = ( # (n_steps, n_layers, n_envs, dim) -> (n_layers, n_seq, dim) self.hidden_states_pi[batch_inds][self.seq_start_indices].reshape(n_layers, n_seq, -1), self.cell_states_pi[batch_inds][self.seq_start_indices].reshape(n_layers, n_seq, -1), ) Where, (n_steps, n_layers, n_envs, dim) ->(n_layers, n_seq, dim). Does it mean that lstm obtains the status information of the whole episode, not the status information of the previous n steps?

Hello, I haven't understood this problem. Can you explain it?
