### ISSUE TITLE
Maskable PPO: Specify masking actions

### ISSUE THREAD

**Issue by gowthamnatarajan** [Stable-Baselines-Team/stable-baselines3-contrib#141] opened 2023-01-31 05:26 UTC
I looked at the documentation on using masking actions but did not understand.
My custom environment has 6 actions. But I would like to mask / disable certain actions based on the current state.

The example I see just says:
env = InvalidActionEnvDiscrete(dim=80, n_invalid_actions=60)

But how do I exactly check the current state and specify invalid actions for that state?

**Comment by araffin** [comment] 2023-01-31 06:33
duplicate of https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/72 (and #102 )

**Closed** 2023-02-01 05:40 UTC
Labels: duplicate, question
