### ISSUE TITLE
[Question] Recurrent Maskable PPO ?!? Rudder ?!?

### ISSUE THREAD

**Issue by tty666** [Stable-Baselines-Team/stable-baselines3-contrib#241] opened 2024-04-30 18:02 UTC
### ❓ Question

Hello,
I am making a lot of test for finRL and using LSTM/GRU into an ActorCritic Policy was one of my first idea but I saw now that you have "maskable" environment.
And in fact if you work on opening trades/closing trades + or multidiscrete actions (% of invest, possible leverage, % stop loss, ...) it makes sense also to mask actions for opening a trade when a trade is already open as an example ...
So I would like to know if for you it would be possible to mix Recurrent PPO and Maskable PPO ?
I am not asking for a feature but more on your expertise about the feasibility of mixing those two particular PPO implementation ?
Also I saw an article about "Rudder" for delayed reward on RL and maybe we could see it implemented also in stable-baselines3 (based also on LSTM for the delayed reward) ? 
[https://ml-jku.github.io/rudder/](https://ml-jku.github.io/rudder/)
Thanks in advance for your answer guys !

(And yes I know about the risk on Financial algorithm - gmabling aspect but it doesn't mean it's not interesting !)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2024-04-30 19:53
duplicate of https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/101

**Closed by araffin** 2024-04-30 19:53 UTC
Labels: duplicate, question, trading warning
