### ISSUE TITLE
How to use maskable PPO

### ISSUE THREAD

**Issue by anilkurkcu** [Stable-Baselines-Team/stable-baselines3-contrib#177] opened 2023-04-14 06:19 UTC
### ❓ Question

I want to determine the actions to be masked out based on my state-space. How can I achieve this?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-04-14 06:46
Duplicate of https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/166
https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/141

#72 and #102

**Closed by araffin** 2023-04-14 06:46 UTC
Labels: duplicate, question, RTFM
